# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovXRjnLzNZhzrmfwWIITxEYyhQsGflsL
"""

#Customer Purchase Validation 4
purchase_amount=float(input("enter puchase amount:"))
if purchase_amount>0:
  print("valid")
else:
  print("invalid",)