# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ecefRpk7pL_gGCdgML0RTSFNG707cH8Z
"""

#Delivery Distance Category 7
delivery_distance=int(input(" delivery distance in km:"))
if delivery_distance<=5:
  print("Local")
elif delivery_distance>=6-20 and delivery_distance==20:
  print("Outstation")
else:
  print("City")