# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xTxz52Z7Zm_H9xqpF2Ctvs7IUlj47kh
"""

#Feedback Count Dashboard 10
feedbacks={
    "Positive":45,
    "Neutral":18,
    "Negative":7,
}
total_feeddback=sum(feedbacks.values())
print("Total Feedbacks:",total_feeddback)
total=max(feedbacks)
print ("Highest Feedback Type:",total)