# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RszZS59iaTHgRuzme9-pOatKrEp5snSV
"""

# Inventory Stock Comparison 5
opening_stock=[200,156,55,399]
closing_stock=[399,58,77,999]
for i in range(len(opening_stock)):
  if closing_stock[i]>opening_stock[i]:
    print(f"product{i+1}: stock increased")
  elif closing_stock[i]<opening_stock[i]:
    print(f"product{i+1}: stock decreased")
  else:
    print(f"product{i+1}: stock remained same")