# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KP7F8umgdUBb0q4QcQv_0RoVr36mSZP
"""

#Online Exam Score Analyzer 8
student_scores=[50,88.5,98,63.23]
total_score=sum(student_scores)
average_score=total_score/len(student_scores)
print("Total Score:",total_score)
print("Average Score:",average_score)
count_of_scores_above_average=0
for score in student_scores:
  if score >= average_score:
    count_of_scores_above_average+=1
print("Number of scores above average:", count_of_scores_above_average)