# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Evz7WVBNh-wWncYPos2DC88VxrPYXOkf
"""

#Online Order Summery Generator 1
item_prices = [199, 1299, 299, 799, 198]
total_order_value = sum(item_prices)
average_price = total_order_value / len(item_prices)
print("Item Prices:", item_prices)
print("Total Order Value: ", total_order_value)
print("Average Item Price: ", average_price)