# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iiYw3Qa7I0lYiKO4U61_ABfT0XUkPD5P
"""

#product price lock system 9
fixed_product_price= (55,99,199,89,299)
print(fixed_product_price[0])
fixed_product_price[1]=54

