# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRXt7uOGSlgXWRo6ooA71FGsLPbZUVpQ
"""

# Student Course Mapping 6
Student_Courses={
     "ravya":"Python",
     "chetya":"Data Analytics",
     "ashya":"AI"
 }
print ("Student Names:")
for Student in Student_Courses.keys():
  print(Student)
print("\nEnrolled Courses:")
for Course in Student_Courses.values():
  print(Course)
student_name=input("Enter student Name:")
if student_name in Student_Courses:
  print(f"\n{student_name} is enrolled in {Student_Courses[student_name]}")
else:
  print(f"\n{student_name} is not enrolled in any courses")